const fs = require('fs');
const net = require('net');

// tcpip.mr 里 dltype=3 默认连 13230；dltype=2 会连 13229。
const port = Number(process.env.PORT || 13230);
const tunnelAck = 'HTTP/1.1 200 Connection established\r\n\r\n';

function u32le(value) {
    const buf = Buffer.alloc(4);
    buf.writeUInt32LE(value >>> 0, 0);
    return buf;
}

function fixedString(value, len) {
    const buf = Buffer.alloc(len);
    Buffer.from(value, 'ascii').copy(buf, 0, 0, len - 1);
    return buf;
}

function parseHandshake(line) {
    const result = {};
    const body = line.startsWith('set ') ? line.slice(4) : line;
    for (const kv of body.split(',')) {
        const eq = kv.indexOf('=');
        if (eq !== -1) {
            result[kv.slice(0, eq).trim()] = kv.slice(eq + 1).trim();
        }
    }
    return result;
}

function makeMrpPackage(files, info = {}) {
    const names = Object.keys(files);
    const indexLen = names.reduce((sum, name) => sum + Buffer.byteLength(name, 'ascii') + 1 + 16, 0);
    const dataStart = 240 + indexLen;
    const headerFileStart = dataStart - 8;
    const records = [];
    const dataRecords = [];
    let dataPos = dataStart;

    for (const name of names) {
        const nameBuf = Buffer.from(`${name}\0`, 'ascii');
        const body = Buffer.isBuffer(files[name]) ? files[name] : Buffer.from(String(files[name]), 'utf8');
        const filePos = dataPos + 4 + nameBuf.length + 4;

        records.push(Buffer.concat([
            u32le(nameBuf.length),
            nameBuf,
            u32le(filePos),
            u32le(body.length),
            u32le(0),
        ]));
        dataRecords.push(Buffer.concat([
            u32le(nameBuf.length),
            nameBuf,
            u32le(body.length),
            body,
        ]));
        dataPos += 4 + nameBuf.length + 4 + body.length;
    }

    const header = Buffer.alloc(240);
    header.write('MRPG', 0, 'ascii');
    u32le(headerFileStart).copy(header, 4);
    u32le(dataPos).copy(header, 8);
    u32le(240).copy(header, 12);
    fixedString(info.filename || 'applist.mrp', 12).copy(header, 16);
    fixedString(info.appname || 'App List', 24).copy(header, 28);
    fixedString('1234567890', 16).copy(header, 52);
    u32le(info.appid || 1).copy(header, 68);
    u32le(info.version || 1).copy(header, 72);
    fixedString(info.vendor || 'vmrp', 40).copy(header, 88);
    fixedString(info.description || 'Generated app list', 64).copy(header, 128);
    header.writeUInt32BE(info.appid || 1, 192);
    header.writeUInt32BE(info.version || 1, 196);

    return Buffer.concat([header, ...records, ...dataRecords]);
}

function getApplistSource(fields) {
    const clientVer = Number(fields.listver || 0);
    const listver = Number.isFinite(clientVer) ? Math.max(1, clientVer + 1) : 1;
    return [
        `listver = ${listver}`,
        'ignore_all = nil',
        'list = {',
        '  {t = "APP", p = "Game", n = "Demo App", e = "demoapp", v = 1, s = "Demo item from local socket server", ic = 1},',
        '  {t = "APP", p = "Game", n = "Puzzle Game", e = "puzzle", v = 1, s = "Second list item for applist test", ic = 2},',
        '  {t = "APP", p = "Game", n = "Network Tool", e = "nettool", v = 1, s = "Generated by tool/socket-server.js", ic = 3},',
        '}',
        '',
    ].join('\n');
}

function getApplistPackage(fields) {
    if (process.env.APPLIST_MRP_FILE) {
        return fs.readFileSync(process.env.APPLIST_MRP_FILE);
    }

    const source = process.env.APPLIST_SOURCE_FILE
        ? fs.readFileSync(process.env.APPLIST_SOURCE_FILE)
        : Buffer.from(getApplistSource(fields), 'utf8');
    const icons = fs.readFileSync('temp/dsm_gm/lstic.bmp');

    return makeMrpPackage({
        'start.mr': source,
        'icons.bmp': icons,
    }, {
        filename: 'applist.mrp',
        appname: 'App List',
        appid: 1,
        version: Number(fields.listver || 0) + 1 || 1,
        vendor: 'vmrp',
        description: 'Generated app list',
    });
}

function escapeMrString(buf) {
    let out = '';
    for (const byte of buf) {
        out += `\\${byte.toString(10).padStart(3, '0')}`;
    }
    return out;
}

function chunkBuffer(buf, size) {
    const chunks = [];
    for (let offset = 0; offset < buf.length; offset += size) {
        chunks.push(buf.slice(offset, offset + size));
    }
    return chunks;
}

function hasCustomCodePayload() {
    return Boolean(process.env.CODE_PAYLOAD_FILE || process.env.CODE_PAYLOAD_HEX || process.env.CODE_PAYLOAD);
}

function getCodePayload(fields) {
    if (process.env.CODE_PAYLOAD_FILE) {
        return fs.readFileSync(process.env.CODE_PAYLOAD_FILE);
    }
    if (process.env.CODE_PAYLOAD_HEX) {
        return Buffer.from(process.env.CODE_PAYLOAD_HEX.replace(/\s+/g, ''), 'hex');
    }
    if (process.env.CODE_PAYLOAD) {
        return Buffer.from(process.env.CODE_PAYLOAD, 'utf8');
    }

    // tcpip.mr 的 cmd 表只在本文件里注册了 cmd.code。
    // 真实服务端的 code 数据会经 TestCom1(300, data) 处理后 _loads(data) 执行。
    // 默认 payload 用来确认分发路径，并注册 progress 命令。
    return Buffer.from(
        [
            `print("code frame received: dltype=${fields.dltype}, listver=${fields.listver}")`,
            'def progress(data)',
            '  p = tonumber(data)',
            '  if p == nil then',
            '    p = 0',
            '  end',
            '  if g_dialog then',
            '    if g_dialog.update then',
            '      g_dialog.update(g_dialog, nil, data .. "%", p)',
            '    end',
            '  end',
            '  if win then',
            '    if win.refresh then',
            '      win.refresh()',
            '    end',
            '  end',
            'end',
            'cmd.progress = progress',
        ].join('\n'),
        'utf8',
    );
}

function getSuccessExitPayload() {
    return [
        'if net then',
        '  if net.successexit then',
        '    net.successexit()',
        '  end',
        'end',
    ].join('\n');
}

function getApplistInstallPayload(fields) {
    const pack = getApplistPackage(fields);
    const lines = [
        `print("writing applist.mrp bytes=${pack.length}")`,
        'sys.rm("applist.mrp")',
        'f = file.open("applist.mrp", 10)',
        'if f then',
    ];

    for (const chunk of chunkBuffer(pack, 512)) {
        lines.push(`  f.write(f, "${escapeMrString(chunk)}")`);
    }

    lines.push(
        '  f.close(f)',
        '  if g_dialog then',
        '    if g_dialog.update then',
        '      g_dialog.update(g_dialog, nil, "100%", 100)',
        '    end',
        '  end',
        '  if recreateApplist then',
        '    recreateApplist(1)',
        '  else',
        ...getSuccessExitPayload().split('\n').map(line => `    ${line}`),
        '  end',
        'else',
        '  if net then',
        '    if net.fail then',
        '      net.fail()',
        '    end',
        '  end',
        'end',
    );

    return lines.join('\n');
}

function getFinishPayload(fields) {
    if (String(fields.dltype) === '3' && process.env.DEMO_APPLIST !== '0') {
        return Buffer.from(getApplistInstallPayload(fields), 'utf8');
    }
    return Buffer.from(getSuccessExitPayload(), 'utf8');
}

// CmdRun 解析格式：
//   total = byte(recvbuf, cmdpos) * 256 + byte(recvbuf, cmdpos + 1) + 2
//   space = string.find(recvbuf, " ", cmdpos + 2)
//   thiscmd = string.sub(recvbuf, cmdpos + 2, space - 1)
//   data = string.sub(recvbuf, space + 1, cmdpos + total - 1)
function makeFrame(command, data) {
    const commandBuf = Buffer.from(`${command} `, 'ascii');
    const dataBuf = Buffer.isBuffer(data) ? data : Buffer.from(String(data), 'utf8');
    const len = commandBuf.length + dataBuf.length;

    if (len > 0xffff) {
        throw new RangeError(`frame too large: ${len} bytes`);
    }

    const frame = Buffer.alloc(2 + len);
    frame.writeUInt16BE(len, 0);
    commandBuf.copy(frame, 2);
    dataBuf.copy(frame, 2 + commandBuf.length);
    return frame;
}

function preview(buf, max = 96) {
    const head = buf.slice(0, max);
    const text = head.toString('utf8').replace(/\r/g, '\\r').replace(/\n/g, '\\n');
    return `${buf.length} bytes hex=${head.toString('hex')} text="${text}"`;
}

function sendFrame(socket, command, data) {
    const frame = makeFrame(command, data);
    socket.write(frame);
    const payloadLen = frame.length - 2;
    console.log(`[SEND FRAME] ${command} payload=${payloadLen} total=${frame.length}`);
}

function sendInitialResponse(socket, fields) {
    const payload = getCodePayload(fields);
    const frameDelay = Number(process.env.FRAME_DELAY_MS || 300);

    // 稍微延迟，避免代理 ACK、握手响应和业务帧被客户端一次 receive 到。
    // tcpip.mr 的 CMWAP 首包处理会先找 "\r\n\r\n"，业务帧放后续包最稳。
    setTimeout(() => {
        if (!socket.destroyed) {
            sendFrame(socket, 'code', payload);
        }
    }, frameDelay);

    if (hasCustomCodePayload() || process.env.DEMO_PROGRESS === '0') {
        return;
    }

    const steps = [10, 30, 60, 90, 100];
    const stepDelay = Number(process.env.PROGRESS_DELAY_MS || 700);

    steps.forEach((value, index) => {
        setTimeout(() => {
            if (!socket.destroyed) {
                sendFrame(socket, 'progress', String(value));
            }
        }, frameDelay + stepDelay * (index + 1));
    });

    setTimeout(() => {
        if (!socket.destroyed) {
            sendFrame(socket, 'code', getFinishPayload(fields));
        }
    }, frameDelay + stepDelay * (steps.length + 1));
}

net.createServer((socket) => {
    console.log(`\n[CONNECT] ${socket.remoteAddress}:${socket.remotePort}`);
    socket.setNoDelay(true);

    // detect: 自动识别 CMWAP CONNECT 或直接 set 握手。
    // handshake: 等待 "set dltype=..." 行。
    // data: 握手后记录客户端额外数据。
    let state = 'detect';
    let buf = Buffer.alloc(0);

    function handleHandshakeLine(line) {
        console.log(`[HANDSHAKE] ${line}`);

        if (!line.startsWith('set ')) {
            console.error(`[ERROR] 非法握手包，期望 "set ..."，收到: "${line}"`);
            socket.end();
            return false;
        }

        const fields = parseHandshake(line);
        const required = ['dltype', 'listver', 'scrsize', 'IMEI', 'IMSI'];
        const missing = required.filter(k => !(k in fields));
        if (missing.length > 0) {
            console.error(`[ERROR] 缺少字段: ${missing.join(', ')}`);
            socket.end();
            return false;
        }

        console.log('[FIELDS]', fields);
        console.log(`[OK] 握手成功 dltype=${fields.dltype} listver=${fields.listver} scrsize=${fields.scrsize}`);
        state = 'data';
        sendInitialResponse(socket, fields);
        return true;
    }

    function pump() {
        while (!socket.destroyed) {
            if (state === 'detect') {
                const head = buf.slice(0, Math.min(buf.length, 16)).toString('ascii');

                if (head.startsWith('CONNECT ')) {
                    const eoh = buf.indexOf('\r\n\r\n');
                    if (eoh === -1) return;

                    const firstLine = buf.slice(0, buf.indexOf('\r\n')).toString('utf8');
                    console.log(`[TUNNEL REQ] ${firstLine}`);
                    socket.write(tunnelAck);
                    console.log(`[TUNNEL ACK] ${tunnelAck.trim().replace(/\r\n/g, ' | ')}`);
                    buf = buf.slice(eoh + 4);
                    state = 'handshake';
                    continue;
                }

                if (head.startsWith('set ')) {
                    state = 'handshake';
                    continue;
                }

                if (buf.length < 8) return;

                console.error(`[ERROR] 未识别的首包: ${preview(buf)}`);
                socket.end();
                return;
            }

            if (state === 'handshake') {
                const nl = buf.indexOf('\n');
                if (nl === -1) return;

                const line = buf.slice(0, nl).toString('utf8').replace(/\r$/, '').trim();
                buf = buf.slice(nl + 1);
                if (line.length === 0) continue;

                if (!handleHandshakeLine(line)) return;
                continue;
            }

            if (state === 'data') {
                if (buf.length > 0) {
                    console.log(`[CLIENT DATA] ${preview(buf)}`);
                    buf = Buffer.alloc(0);
                }
                return;
            }
        }
    }

    socket.on('data', (chunk) => {
        buf = Buffer.concat([buf, chunk]);
        pump();
    });

    socket.on('end', () => console.log('[DISCONNECT]'));
    socket.on('error', err => console.error(`[SOCKET ERROR] ${err.message}`));

}).listen(port, () => {
    console.log(`TCP server running at localhost:${port}`);
    console.log('Use CODE_PAYLOAD_FILE, CODE_PAYLOAD_HEX, or CODE_PAYLOAD to replace the default code payload.');
});
